//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeluqueria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasePeluqueriaEntities : DbContext
    {
        public DatabasePeluqueriaEntities()
            : base("name=DatabasePeluqueriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Insumo> Insumo { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Razon_retiro_producto> Razon_retiro_producto { get; set; }
        public virtual DbSet<Registro_compra> Registro_compra { get; set; }
        public virtual DbSet<registro_tratamiento_cliente> registro_tratamiento_cliente { get; set; }
        public virtual DbSet<Retirar_producto> Retirar_producto { get; set; }
        public virtual DbSet<Rol_empleado> Rol_empleado { get; set; }
        public virtual DbSet<Tipo_tratamiento> Tipo_tratamiento { get; set; }
    }
}
